added non-external-id statement count as a signal
wikimedia/articlequality pull request #154
Opened 2020-08-31 15:10 UTC by guergana

2020-09-01 11:47 UTC, micgro42 commented
Could we adjust its name to include `non-external-id` in some way? Because currently it is named in a way that would imply it duplicates what we do in [wikibase.py#L5](https://github.com/wikimedia/articlequality/blob/581a2aaa14eecb692588956a66bbdde74a278fc1/articlequality/feature_lists/wikibase.py#L5): count all the statements of all the properties.

2020-09-09 10:23 UTC, mariushoch requested changes

2020-09-09 10:23 UTC, mariushoch commented on articlequality/feature_lists/wikidatawiki.py
> +"`int` : A count of all statements in the revision"
Not quite accurate

2020-09-09 10:23 UTC, mariushoch commented on articlequality/feature_lists/wikidatawiki.py
> +    name + ".revision.statements",
Should be the same as the var name

2020-09-09 10:23 UTC, mariushoch commented on articlequality/feature_lists/wikidatawiki.py
> +non_external_statements = Datasource(
I think `non_external_id_statements` would be even clearer here.

2020-09-09 10:29 UTC, guergana commented on articlequality/feature_lists/wikidatawiki.py
> +"`int` : A count of all statements in the revision"
You are right!

2020-09-09 10:53 UTC, mariushoch approved these changes

2020-09-09 11:12 UTC, merged